### ISSUE TITLE
Antlr4 grammar missing

### ISSUE THREAD

**Issue by stevej2608** [ttiimm/cymbol#1]
Hi,

The Antlr 4 grammar file is missing from the source tree. The derived A4 lexer & parser are in cymbol.jar but I cannot find the associated grammar.

Can you upload the grammar so the project can be built using the latest version of Antlr 4.

Thanks, Steve

**Comment by ttiimm** [comment]
Hi Steve,

The grammar file is located here:

https://github.com/ttiimm/cymbol/blob/master/src/cymbol/compiler/Cymbol.g

Let me know if there is anything else I could help with.

Tim

**Comment by stevej2608** [comment]
Hi Tim,

Thanks for getting back. The Cymbol.g grammar is Antlr 3 not Antlr 4. 
The Antlr parser contained in cymbol.jar is an A4 parser so I figured it 
must have been generated from an A4 grammar (Cymbol.g4?).

I now know it's easy enough to convert the A3 grammar to A4 which is 
what I've done. As Terence Parr says "basically you just delete anything 
the A4 generator complains about". I was just worried that you might 
have enhanced/improved the grammar. If so I would not be able to pick up 
these changes.

Cheers, Steve

**Comment by ttiimm** [comment]
Ah OK.  I wrote the grammar while Antlr was in a beta version.  I don't
recall which version though.  But it was in Spring 2012 semester. I haven't
had time to update with the latest release.

Tim

**Comment by ttiimm** [comment]
Fixed with https://github.com/ttiimm/cymbol/pull/2
